var first_number=20;
var second_number=10;
var sum=first_number+second_number;
var subtract=first_number-second_number;
var multiply=first_number*second_number;
var division=first_number/second_number;
console.log("sum of two numbers:"+sum);
console.log("Subtraction of two numbers:"+subtract);
console.log("Multiplication of two numbers:"+multiply);
console.log("division of two numbers:"+division);
