var first_number=20;
var second_number=10;
var sum=first_number+second_number;
var subtract=first_number-second_number;
var multiply=first_number*second_number;
var division=first_number/second_number;
console.log(sum);
console.log(subtract);
console.log(multiply);
console.log(division);
